AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Environment:
    Description: Defines environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - beta
      - prod
    ConstraintDescription: Use valid environment [dev, qa, beta, prod]

  NumberOfInstances:
    Description: Number of instances to launch
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 5
    ConstraintDescription: Must be between 1 and 5

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsLab: !Or [ !Equals [ dev, !Ref Environment ], !Equals [ qa, !Ref Environment ], !Equals [ beta, !Ref Environment ] ]
  IsLab2: !Not [ !Equals [ prod, !Ref Environment ] ]
  IsLab3: !Not [ !Conditions IsProd ]

Resources:
  DemoBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: NumberOfInstances
          Value: !Ref NumberOfInstances
          Value: !Ref NumberOfInstances